// 營建物料成本估算常數定義
// 自動提取自 CostEstimator.jsx
import { Paintbrush, Hammer, Layers, Wrench, GlassWater, Package } from 'lucide-react';

const DEFAULT_MATERIALS = {
  // ===== 營建工程 - 結構工程 =====
  混凝土: [
    {
      id: 101,
      name: '預拌混凝土',
      spec: '2000psi (140kgf/cm²)',
      unit: 'm³',
      suggestedPrice: 2800,
      price: 2800,
      note: '地坪/車道/人行道',
      regulation: '非結構用途，適用於人行道、車道、輕載地坪',
    },
    {
      id: 102,
      name: '預拌混凝土',
      spec: '3000psi (210kgf/cm²)',
      unit: 'm³',
      suggestedPrice: 3200,
      price: 3200,
      note: '標準結構/樓板/梁柱',
      regulation: '建構規則§352：一般結構用途，樓板/梁/柱基本強度',
    },
    {
      id: 103,
      name: '預拌混凝土',
      spec: '4000psi (280kgf/cm²)',
      unit: 'm³',
      suggestedPrice: 3800,
      price: 3800,
      note: '高層主結構/地下室',
      regulation: '建構規則§352：高層建築主結構、地下室、重載構件',
    },
    {
      id: 104,
      name: '預拌混凝土',
      spec: '5000psi (350kgf/cm²)',
      unit: 'm³',
      suggestedPrice: 4500,
      price: 4500,
      note: '橋梁/預力構件',
      regulation: '預力混凝土構件、橋梁、特殊結構用途',
    },
    {
      id: 105,
      name: '預拌混凝土',
      spec: 'SCC自充填',
      unit: 'm³',
      suggestedPrice: 4800,
      price: 4800,
      note: '密配筋/複雜造型',
      regulation: '密配筋區域或複雜造型，免振動搗實',
    },
    {
      id: 106,
      name: '素混凝土墊層',
      spec: 'PC (無配筋)',
      unit: 'm³',
      suggestedPrice: 2200,
      price: 2200,
      note: '打底/保護層',
      regulation: '基礎打底層、管線保護層，無結構需求',
    },
    {
      id: 107,
      name: '泵浦車壓送',
      spec: '依公尺計',
      unit: 'm',
      suggestedPrice: 250,
      price: 250,
      note: '另收出車費$8,000~$12,000',
      regulation: '',
    },
    {
      id: 108,
      name: '混凝土澆置',
      spec: '純工資',
      unit: 'm³',
      suggestedPrice: 450,
      price: 450,
      note: '震動搗實+整平',
      regulation: '澆置後需充分振動搗實，避免蜂窩',
    },
  ],
  鋼筋: [
    {
      id: 111,
      name: '竹節鋼筋 #3',
      spec: 'D10 (9.53mm/0.56kg/m)',
      unit: 'kg',
      suggestedPrice: 17,
      price: 17,
      note: '箍筋/繫筋',
      regulation: '建構規則§427：箍筋間距≤d/4且≤10cm（塑鉸區）',
    },
    {
      id: 112,
      name: '竹節鋼筋 #4',
      spec: 'D13 (12.7mm/0.99kg/m)',
      unit: 'kg',
      suggestedPrice: 17,
      price: 17,
      note: '繫筋/副筋',
      regulation: '繫筋應錨定於箍筋圍束範圍內',
    },
    {
      id: 113,
      name: '竹節鋼筋 #5',
      spec: 'D16 (15.9mm/1.56kg/m)',
      unit: 'kg',
      suggestedPrice: 16.5,
      price: 16.5,
      note: '一般主筋',
      regulation: '建構規則§422：梁最小受拉筋比≥0.40%',
    },
    {
      id: 114,
      name: '竹節鋼筋 #6',
      spec: 'D19 (19.1mm/2.25kg/m)',
      unit: 'kg',
      suggestedPrice: 16.5,
      price: 16.5,
      note: '主筋',
      regulation: '建構規則§426：柱最小配筋率≥0.80%',
    },
    {
      id: 115,
      name: '竹節鋼筋 #7',
      spec: 'D22 (22.2mm/3.04kg/m)',
      unit: 'kg',
      suggestedPrice: 16,
      price: 16,
      note: '大樑主筋',
      regulation: '大樑主筋需考慮抗剪設計',
    },
    {
      id: 116,
      name: '竹節鋼筋 #8',
      spec: 'D25 (25.4mm/3.98kg/m)',
      unit: 'kg',
      suggestedPrice: 16,
      price: 16,
      note: '柱主筋',
      regulation: '柱主筋不少於4根，淨間距≥4cm',
    },
    {
      id: 117,
      name: '竹節鋼筋 #9',
      spec: 'D29 (28.7mm/5.08kg/m)',
      unit: 'kg',
      suggestedPrice: 16,
      price: 16,
      note: '特大柱/基礎',
      regulation: '基礎筋保護層≥7.5cm（土壤接觸）',
    },
    {
      id: 118,
      name: '竹節鋼筋 #10',
      spec: 'D32 (32.2mm/6.39kg/m)',
      unit: 'kg',
      suggestedPrice: 16,
      price: 16,
      note: '重型結構',
      regulation: '重型結構需考慮續接器或搭接',
    },
    {
      id: 119,
      name: '鋼筋綁紮',
      spec: '純工資 (依噸計)',
      unit: 'ton',
      suggestedPrice: 8500,
      price: 8500,
      note: '含鐵絲',
      regulation: '',
    },
    {
      id: 120,
      name: '鋼筋加工',
      spec: '彎折/裁切',
      unit: 'ton',
      suggestedPrice: 2000,
      price: 2000,
      note: '機械加工',
      regulation: '彎折半徑依鋼筋號數規定',
    },
    {
      id: 121,
      name: '鋼筋續接器',
      spec: '機械接頭',
      unit: '組',
      suggestedPrice: 150,
      price: 150,
      note: 'SA級',
      regulation: 'CNS 560 SA級續接器規範',
    },
  ],
  模板: [
    {
      id: 131,
      name: '普通木模板',
      spec: '樓板/牆體',
      unit: 'm²',
      suggestedPrice: 800,
      price: 800,
      note: '夾板模+支撐+工資',
      regulation: '撓度承載後≤跨距1/240',
    },
    {
      id: 132,
      name: '清水模板',
      spec: '外觀面要求',
      unit: 'm²',
      suggestedPrice: 1100,
      price: 1100,
      note: '特殊處理面',
      regulation: '外觀面需使用高品質面板',
    },
    {
      id: 133,
      name: '柱模板',
      spec: '方柱/矩形柱',
      unit: 'm²',
      suggestedPrice: 900,
      price: 900,
      note: '含組立+拆模',
      regulation: '柱牆拆模：約1-3天（需達設計強度）',
    },
    {
      id: 134,
      name: '樑模板',
      spec: '大樑/小樑',
      unit: 'm²',
      suggestedPrice: 850,
      price: 850,
      note: '含底模+側模',
      regulation: '樑樓板拆模：約14-28天（需達70%設計強度）',
    },
    {
      id: 135,
      name: '樓梯模板',
      spec: '階梯面',
      unit: 'm²',
      suggestedPrice: 1000,
      price: 1000,
      note: '複雜造型',
      regulation: '樓梯踏面需精確量測',
    },
    {
      id: 136,
      name: '系統模板',
      spec: '鋁模/鋼模租用',
      unit: 'm²',
      suggestedPrice: 450,
      price: 450,
      note: '重複使用30次以上',
      regulation: '重複使用可降低成本',
    },
    {
      id: 137,
      name: '模板支撐架',
      spec: '鋼管鷹架',
      unit: '組',
      suggestedPrice: 120,
      price: 120,
      note: '含組立拆除',
      regulation: '高支模≥7m/330m²需技師簽章設計',
    },
    {
      id: 138,
      name: '曲面模板',
      spec: '特殊造型',
      unit: 'm²',
      suggestedPrice: 1500,
      price: 1500,
      note: '客製化加工',
      regulation: '客製化造型需專案設計',
    },
  ],
  // ===== 營建工程 - 泥作工程 =====
  泥作材料: [
    {
      id: 141,
      name: '水泥',
      spec: '40kg/包',
      unit: '包',
      suggestedPrice: 185,
      price: 185,
      note: '台泥/亞泥 (2023年起業界標準)',
      regulation: 'CNS 61：卜特蘭水泥規範',
    },
    {
      id: 142,
      name: '河砂 (細砂)',
      spec: '粉光用',
      unit: '立方',
      suggestedPrice: 1400,
      price: 1400,
      note: '過篩',
      regulation: 'CNS 1240：混凝土用細粒料',
    },
    {
      id: 143,
      name: '河砂 (粗砂)',
      spec: '打底用',
      unit: '立方',
      suggestedPrice: 1200,
      price: 1200,
      note: '未過篩',
      regulation: 'CNS 1240：混凝土用粒料',
    },
    {
      id: 144,
      name: '紅磚',
      spec: '230x110x60mm',
      unit: '塊',
      suggestedPrice: 7.5,
      price: 7.5,
      note: '128塊/m² (1B牆)',
      regulation: 'CNS 382：普通磚規範',
    },
    {
      id: 145,
      name: '輕質磚',
      spec: '60x20x10cm (ALC)',
      unit: '塊',
      suggestedPrice: 35,
      price: 35,
      note: '隔間牆用',
      regulation: '輕質混凝土磚，需考慮承重限制',
    },
    {
      id: 146,
      name: '空心磚',
      spec: '40x20x10cm',
      unit: '塊',
      suggestedPrice: 18,
      price: 18,
      note: '輕隔間',
      regulation: 'CNS 1002：空心混凝土砌塊',
    },
    {
      id: 147,
      name: '水泥砂漿 1:3',
      spec: '打底用',
      unit: 'm³',
      suggestedPrice: 3800,
      price: 3800,
      note: '含攪拌',
      regulation: '打底層厚度約15-20mm',
    },
    {
      id: 148,
      name: '水泥砂漿 1:2',
      spec: '粉光面',
      unit: 'm³',
      suggestedPrice: 4200,
      price: 4200,
      note: '細緻面層',
      regulation: '粉光層厚度約5-8mm',
    },
    {
      id: 149,
      name: '牆壁打底',
      spec: '1:3水泥整平',
      unit: '坪',
      suggestedPrice: 3500,
      price: 3500,
      note: '連工帶料',
      regulation: '施工前需潤濕基面',
    },
    {
      id: 150,
      name: '牆壁粉光',
      spec: '1:2水泥粉光',
      unit: '坪',
      suggestedPrice: 2000,
      price: 2000,
      note: '純工資',
      regulation: '粉光前打底需養護3天以上',
    },
    {
      id: 151,
      name: '地面粉光',
      spec: '1:2水泥粉光',
      unit: '坪',
      suggestedPrice: 2500,
      price: 2500,
      note: '純工資',
      regulation: '地坪粉光需考慮洩水坡度',
    },
    {
      id: 152,
      name: '砌磚工資',
      spec: '紅磚',
      unit: 'm²',
      suggestedPrice: 650,
      price: 650,
      note: '不含材料',
      regulation: '砌磚灰縫寬度8-12mm',
    },
    {
      id: 153,
      name: '砌磚工資',
      spec: '輕質磚',
      unit: 'm²',
      suggestedPrice: 450,
      price: 450,
      note: '不含材料',
      regulation: '輕質磚需使用專用黏著劑',
    },
  ],
  // ===== 營建工程 - 磁磚工程 =====
  磁磚材料: [
    {
      id: 161,
      name: '磁磚 30x30cm',
      spec: '地磚',
      unit: 'm²',
      suggestedPrice: 350,
      price: 350,
      note: '經濟款',
      regulation: 'CNS 9737：陶瓷面磚規範',
    },
    {
      id: 162,
      name: '磁磚 30x60cm',
      spec: '壁磚',
      unit: 'm²',
      suggestedPrice: 450,
      price: 450,
      note: '浴室/廚房',
      regulation: 'CNS 9737：壁磚吸水率≤10%',
    },
    {
      id: 163,
      name: '磁磚 60x60cm',
      spec: '拋光石英磚',
      unit: 'm²',
      suggestedPrice: 650,
      price: 650,
      note: '客廳/商空',
      regulation: '石英磚吸水率≤0.5%',
    },
    {
      id: 164,
      name: '磁磚 80x80cm',
      spec: '拋光石英磚',
      unit: 'm²',
      suggestedPrice: 850,
      price: 850,
      note: '大空間',
      regulation: '大尺寸需使用乾式/半乾式工法',
    },
    {
      id: 165,
      name: '磁磚 60x120cm',
      spec: '大板磚',
      unit: 'm²',
      suggestedPrice: 1200,
      price: 1200,
      note: '豪宅/飯店',
      regulation: '大板磚需專用背膠，乾式施工',
    },
    {
      id: 166,
      name: '磁磚 120x240cm',
      spec: '岩板',
      unit: 'm²',
      suggestedPrice: 2500,
      price: 2500,
      note: '電視牆/檯面',
      regulation: '岩板需專業施工團隊',
    },
    {
      id: 167,
      name: '馬賽克磚',
      spec: '2.3x2.3cm',
      unit: 'm²',
      suggestedPrice: 550,
      price: 550,
      note: '外牆/泳池',
      regulation: '外牆用需抗凍融性',
    },
    {
      id: 168,
      name: '六角磚',
      spec: '造型磚',
      unit: 'm²',
      suggestedPrice: 800,
      price: 800,
      note: '特殊拼貼',
      regulation: '造型磚施工損耗約10-15%',
    },
    {
      id: 169,
      name: '木紋磚',
      spec: '20x120cm',
      unit: 'm²',
      suggestedPrice: 650,
      price: 650,
      note: '仿木地板',
      regulation: '木紋磚可交丁/平舖',
    },
    {
      id: 170,
      name: '益膠泥',
      spec: '25kg/包 (貼4-5m²)',
      unit: '包',
      suggestedPrice: 480,
      price: 480,
      note: '高黏著力',
      regulation: 'CNS 14646：陶瓷面磚用黏著劑',
    },
    {
      id: 171,
      name: '填縫劑',
      spec: '抗污防霉 (0.3kg/m²)',
      unit: 'kg',
      suggestedPrice: 150,
      price: 150,
      note: 'AB膠/環氧',
      regulation: '浴室建議使用抗霉填縫劑',
    },
    {
      id: 172,
      name: '磁磚施工',
      spec: '濕式工法 (軟底)',
      unit: 'm²',
      suggestedPrice: 850,
      price: 850,
      note: '純工資',
      regulation: '軟底適用≤60cm磁磚',
    },
    {
      id: 173,
      name: '磁磚施工',
      spec: '乾式工法 (硬底)',
      unit: 'm²',
      suggestedPrice: 1100,
      price: 1100,
      note: '純工資/大板用',
      regulation: '硬底適用60cm以上大板磚',
    },
    {
      id: 174,
      name: '磁磚施工',
      spec: '半濕式 (騷底)',
      unit: 'm²',
      suggestedPrice: 950,
      price: 950,
      note: '純工資',
      regulation: '騷底介於軟硬底之間',
    },
    {
      id: 175,
      name: '壁磚施工',
      spec: '連工帶料',
      unit: '坪',
      suggestedPrice: 3800,
      price: 3800,
      note: '含磁磚',
      regulation: '壁磚需由下往上鋪貼',
    },
    {
      id: 176,
      name: '地磚施工',
      spec: '連工帶料',
      unit: '坪',
      suggestedPrice: 5500,
      price: 5500,
      note: '含磁磚',
      regulation: '地磚應預留伸縮縫',
    },
  ],
  // ===== 營建工程 - 塗料工程 =====
  塗料材料: [
    {
      id: 181,
      name: '外牆彈性漆',
      spec: '5加侖 (塗刷20坪)',
      unit: '桶',
      suggestedPrice: 4500,
      price: 4500,
      note: '抗UV/防水',
      regulation: '外牆塗料應符合CNS 4940',
    },
    {
      id: 182,
      name: '外牆平光漆',
      spec: '5加侖 (塗刷22坪)',
      unit: '桶',
      suggestedPrice: 3200,
      price: 3200,
      note: '一般外牆',
      regulation: '平光漆適合遮蓋牆面瑕疵',
    },
    {
      id: 183,
      name: '內牆乳膠漆',
      spec: '5加侖 (塗刷25坪)',
      unit: '桶',
      suggestedPrice: 2200,
      price: 2200,
      note: '室內用',
      regulation: '室內塗料VOC≤50g/L（綠建材）',
    },
    {
      id: 184,
      name: '水泥漆',
      spec: '5加侖 (塗刷30坪)',
      unit: '桶',
      suggestedPrice: 1500,
      price: 1500,
      note: '經濟款',
      regulation: '水泥漆透氣性較差',
    },
    {
      id: 185,
      name: '防水漆',
      spec: '5加侖',
      unit: '桶',
      suggestedPrice: 3800,
      price: 3800,
      note: '屋頂/浴室',
      regulation: '防水漆需塗刷2-3道',
    },
    {
      id: 186,
      name: '底漆',
      spec: '5加侖',
      unit: '桶',
      suggestedPrice: 1800,
      price: 1800,
      note: '增加附著力',
      regulation: '新牆必須先上底漆',
    },
    {
      id: 187,
      name: '批土',
      spec: '25kg/包 (批15坪)',
      unit: '包',
      suggestedPrice: 380,
      price: 380,
      note: '牆面整平',
      regulation: '批土後需打磨平整',
    },
    {
      id: 188,
      name: '砂紙/研磨',
      spec: '依坪計',
      unit: '坪',
      suggestedPrice: 80,
      price: 80,
      note: '牆面處理',
      regulation: '批土後需用180-240號砂紙',
    },
    {
      id: 189,
      name: '外牆塗裝',
      spec: '純工資',
      unit: '坪',
      suggestedPrice: 650,
      price: 650,
      note: '含底漆+面漆2度',
      regulation: '外牆施工需注意天候',
    },
    {
      id: 190,
      name: '內牆塗裝(水泥漆)',
      spec: '新作全批土',
      unit: '坪',
      suggestedPrice: 1200,
      price: 1200,
      note: '連工帶料',
      regulation: '全批土工序：批土→打磨→底漆→面漆',
    },
    {
      id: 191,
      name: '內牆塗裝(乳膠漆)',
      spec: '新作全批土',
      unit: '坪',
      suggestedPrice: 1900,
      price: 1900,
      note: '連工帶料',
      regulation: '乳膠漆較環保，VOC低',
    },
    {
      id: 192,
      name: '舊牆翻新(乳膠漆)',
      spec: '局部批土',
      unit: '坪',
      suggestedPrice: 1500,
      price: 1500,
      note: '連工帶料',
      regulation: '舊牆需先刮除鬆動漆膜',
    },
    {
      id: 193,
      name: '鷹架租用',
      spec: '外牆施工',
      unit: '坪',
      suggestedPrice: 250,
      price: 250,
      note: '按牆面積計',
      regulation: '高度≥2m需搭設施工架',
    },
  ],
  // ===== 營建工程 - 防水工程 =====
  防水材料: [
    {
      id: 201,
      name: '防水漆',
      spec: '壓克力樹脂',
      unit: '坪',
      suggestedPrice: 800,
      price: 800,
      note: '施工方便/耐用度低',
      regulation: '施工前需清除油污、乾燥',
    },
    {
      id: 202,
      name: 'PU防水',
      spec: '聚氨酯',
      unit: '坪',
      suggestedPrice: 2200,
      price: 2200,
      note: '頂樓用/注意含水率',
      regulation: 'CNS 6986：建築防水用聚胺酯',
    },
    {
      id: 203,
      name: '改質瀝青防水毯',
      spec: '10-15年壽命',
      unit: '坪',
      suggestedPrice: 3200,
      price: 3200,
      note: '耐候性高',
      regulation: 'CNS 14497：改質瀝青防水氈',
    },
    {
      id: 204,
      name: '防水毯',
      spec: '聚酯纖維+瀝青',
      unit: '坪',
      suggestedPrice: 12000,
      price: 12000,
      note: '效果最佳',
      regulation: 'CNS 10410：油毛氈紙規範',
    },
    {
      id: 205,
      name: '彈性水泥',
      spec: '浴室用',
      unit: '坪',
      suggestedPrice: 2500,
      price: 2500,
      note: '塗刷2-3層',
      regulation: '浴室應具防水設計，高度至用水器具以上',
    },
    {
      id: 206,
      name: '結晶型防水',
      spec: '20年壽命',
      unit: '坪',
      suggestedPrice: 3500,
      price: 3500,
      note: '地下室用',
      regulation: '地下室應採外防水為原則',
    },
    {
      id: 207,
      name: '水泥系滲透劑',
      spec: '結構補強',
      unit: '坪',
      suggestedPrice: 2000,
      price: 2000,
      note: '舊樓修繕',
      regulation: '舊樓修繕用',
    },
    {
      id: 208,
      name: '高壓灌注',
      spec: '裂縫處理',
      unit: '針',
      suggestedPrice: 600,
      price: 600,
      note: '打針填補',
      regulation: '裂縫灌注修補',
    },
    {
      id: 209,
      name: '壁癌處理',
      spec: '含刮除/補強',
      unit: '坪',
      suggestedPrice: 3000,
      price: 3000,
      note: '依嚴重度',
      regulation: '壁癌應先找出滲水源頭',
    },
    {
      id: 210,
      name: '試水測試',
      spec: '48hr',
      unit: '次',
      suggestedPrice: 3000,
      price: 3000,
      note: '含蓄水/排水',
      regulation: '完工需48小時試水測試',
    },
  ],
  // ===== 營建工程 - 門窗工程 =====
  門窗材料: [
    {
      id: 221,
      name: '一般鋁窗',
      spec: '傳統型',
      unit: '才',
      suggestedPrice: 280,
      price: 280,
      note: '不含玻璃/安裝',
      regulation: 'CNS 3092：鋁製門窗規範',
    },
    {
      id: 222,
      name: '氣密窗',
      spec: 'CNS認證',
      unit: '才',
      suggestedPrice: 450,
      price: 450,
      note: '不含玻璃/安裝',
      regulation: 'CNS 11527：氣密性2等級以上',
    },
    {
      id: 223,
      name: '隔音窗',
      spec: 'STC-37db以上',
      unit: '才',
      suggestedPrice: 850,
      price: 850,
      note: '不含玻璃/安裝',
      regulation: 'STC 37db以上具明顯隔音效果',
    },
    {
      id: 224,
      name: '5mm清玻璃',
      spec: '單層',
      unit: '才',
      suggestedPrice: 35,
      price: 35,
      note: '一般隔間',
      regulation: 'CNS 679：平板玻璃',
    },
    {
      id: 225,
      name: '10mm強化玻璃',
      spec: '單層',
      unit: '才',
      suggestedPrice: 85,
      price: 85,
      note: '淋浴間',
      regulation: 'CNS 2213：強化玻璃需標示',
    },
    {
      id: 226,
      name: '5+5mm膠合玻璃',
      spec: '安全玻璃',
      unit: '才',
      suggestedPrice: 120,
      price: 120,
      note: '防盜/隔音',
      regulation: 'CNS 14815：膠合安全玻璃',
    },
    {
      id: 227,
      name: '複層中空玻璃',
      spec: '5+6A+5mm',
      unit: '才',
      suggestedPrice: 180,
      price: 180,
      note: '隔熱/隔音',
      regulation: '中空層氬氣填充效果更佳',
    },
    {
      id: 228,
      name: 'Low-E玻璃',
      spec: '節能',
      unit: '才',
      suggestedPrice: 250,
      price: 250,
      note: '低輻射/節能',
      regulation: '遮蔽係數SC≤0.5為佳',
    },
    {
      id: 229,
      name: '氣密窗安裝',
      spec: '連工帶料',
      unit: '才',
      suggestedPrice: 750,
      price: 750,
      note: '大和賞等級',
      regulation: '安裝需確保氣密水密性',
    },
    {
      id: 230,
      name: '隔音窗安裝',
      spec: '連工帶料',
      unit: '才',
      suggestedPrice: 950,
      price: 950,
      note: '膠合玻璃',
      regulation: '隔音窗框需獨立安裝',
    },
    {
      id: 231,
      name: '紗窗',
      spec: '白色/黑色',
      unit: '才',
      suggestedPrice: 60,
      price: 60,
      note: '不含框',
      regulation: '防蚊紗網建議20目以上',
    },
    {
      id: 232,
      name: '鐵捲門(黑鐵)',
      spec: '傳統手動',
      unit: '才',
      suggestedPrice: 350,
      price: 350,
      note: '含安裝',
      regulation: '需定期防鏽處理',
    },
    {
      id: 233,
      name: '鐵捲門(白鐵)',
      spec: '不鏽鋼電動',
      unit: '才',
      suggestedPrice: 550,
      price: 550,
      note: '含馬達',
      regulation: '電動門需安全裝置',
    },
    {
      id: 234,
      name: '快速捲門',
      spec: '電動',
      unit: '才',
      suggestedPrice: 750,
      price: 750,
      note: '含安全裝置',
      regulation: '快速門需紅外線感應器',
    },
  ],
  // ===== 營建工程 - 拆除清運 =====
  拆除清運: [
    {
      id: 241,
      name: '裝潢廢棄物清運',
      spec: '垃圾車 (5噸)',
      unit: '車',
      suggestedPrice: 16000,
      price: 16000,
      note: '2025年起需申報',
      regulation: '營建廢棄物需合法清運，GPS追蹤',
    },
    {
      id: 242,
      name: '磁磚拆除',
      spec: '壁磚/地磚',
      unit: '坪',
      suggestedPrice: 1200,
      price: 1200,
      note: '純工資',
      regulation: '拆除前需評估結構影響',
    },
    {
      id: 243,
      name: '木作拆除',
      spec: '天花/櫃體',
      unit: '坪',
      suggestedPrice: 800,
      price: 800,
      note: '純工資',
      regulation: '木作可回收再利用',
    },
    {
      id: 244,
      name: '輕隔間拆除',
      spec: '矽酸鈣板',
      unit: '坪',
      suggestedPrice: 600,
      price: 600,
      note: '純工資',
      regulation: '矽酸鈣板需分類處理',
    },
    {
      id: 245,
      name: '磚牆拆除',
      spec: '1B磚牆',
      unit: '坪',
      suggestedPrice: 1800,
      price: 1800,
      note: '純工資',
      regulation: '結構牆不可任意拆除',
    },
    {
      id: 246,
      name: 'RC牆面打除',
      spec: '混凝土',
      unit: '坪',
      suggestedPrice: 3500,
      price: 3500,
      note: '含運棄',
      regulation: '剪力牆/承重牆禁止打除',
    },
    {
      id: 247,
      name: '廢土清運',
      spec: '2025年新制',
      unit: 'm³',
      suggestedPrice: 3000,
      price: 3000,
      note: 'GPS追蹤',
      regulation: '營建剩餘土石方需申報流向',
    },
    {
      id: 248,
      name: '搬運費',
      spec: '人工搬運',
      unit: '趟',
      suggestedPrice: 500,
      price: 500,
      note: '無電梯加價',
      regulation: '',
    },
    {
      id: 249,
      name: '樓層搬運',
      spec: '無電梯',
      unit: '層',
      suggestedPrice: 300,
      price: 300,
      note: '加價',
      regulation: '',
    },
  ],
  // ===== 營建工程 - 建築概估 =====
  建築概估: [
    {
      id: 261,
      name: 'RC透天住宅',
      spec: '2-3F',
      unit: '坪',
      suggestedPrice: 75000,
      price: 75000,
      note: '連工帶料, 中等裝修',
      regulation: '建築技術規則：3層以下免電梯',
    },
    {
      id: 262,
      name: 'RC透天住宅',
      spec: '4-5F',
      unit: '坪',
      suggestedPrice: 85000,
      price: 85000,
      note: '連工帶料, 中等裝修',
      regulation: '4層以上需設電梯或昇降設施',
    },
    {
      id: 263,
      name: 'RC公寓大樓',
      spec: '6-12F',
      unit: '坪',
      suggestedPrice: 95000,
      price: 95000,
      note: '連工帶料, 標準裝修',
      regulation: '6層以上屬高層建築需特別審查',
    },
    {
      id: 264,
      name: 'RC高層大樓',
      spec: '13F以上',
      unit: '坪',
      suggestedPrice: 115000,
      price: 115000,
      note: '連工帶料, 含電梯',
      regulation: '高層建築需特別結構審查',
    },
    {
      id: 265,
      name: '加強磚造',
      spec: '3F以下',
      unit: '坪',
      suggestedPrice: 55000,
      price: 55000,
      note: '農舍/倉庫',
      regulation: '加強磚造限3層以下',
    },
    {
      id: 266,
      name: '鋼構廠房',
      spec: '單層',
      unit: '坪',
      suggestedPrice: 38000,
      price: 38000,
      note: '鋼骨+鋼板屋頂',
      regulation: '鋼構需依CNS鋼材規範',
    },
    {
      id: 267,
      name: '地下室開挖',
      spec: '1層',
      unit: '坪',
      suggestedPrice: 15000,
      price: 15000,
      note: '含擋土+排水',
      regulation: '開挖深度≥1.5m需擋土設施',
    },
    {
      id: 268,
      name: '地下室開挖',
      spec: '2層',
      unit: '坪',
      suggestedPrice: 22000,
      price: 22000,
      note: '含擋土+排水',
      regulation: '深開挖需監測鄰房沉陷',
    },
    {
      id: 269,
      name: '基礎工程',
      spec: '筏式基礎',
      unit: '坪',
      suggestedPrice: 12000,
      price: 12000,
      note: '含開挖回填',
      regulation: '筏基適用軟弱地盤',
    },
    {
      id: 270,
      name: '基礎工程',
      spec: '獨立基腳',
      unit: '坪',
      suggestedPrice: 8000,
      price: 8000,
      note: '一般透天',
      regulation: '獨立基腳需考慮土壤承載力',
    },
  ],
  // ===== 室內裝潢 - 油漆工程 =====
  油漆: [
    {
      id: 301,
      name: '乳膠漆',
      spec: '5加侖桶',
      unit: '加侖',
      suggestedPrice: 1200,
      price: 1200,
      note: '每坪用量約0.5加侖',
      regulation: '室內塗料VOC≤50g/L（綠建材標章）',
    },
    {
      id: 302,
      name: '防水漆',
      spec: '5加侖桶',
      unit: '加侖',
      suggestedPrice: 1800,
      price: 1800,
      note: '浴室/屋頂用',
      regulation: '浴室防水塗層需至少2道',
    },
    {
      id: 303,
      name: '油性漆',
      spec: '加侖',
      unit: '加侖',
      suggestedPrice: 600,
      price: 600,
      note: '金屬/木作',
      regulation: '油性漆VOC較高，需通風施工',
    },
    {
      id: 304,
      name: '調和漆',
      spec: '加侖',
      unit: '加侖',
      suggestedPrice: 450,
      price: 450,
      note: '鐵件底漆',
      regulation: '鐵件需先除鏽再上底漆',
    },
    {
      id: 305,
      name: '護木油',
      spec: '公升',
      unit: 'L',
      suggestedPrice: 350,
      price: 350,
      note: '戶外木作',
      regulation: '戶外木作需定期維護',
    },
    {
      id: 306,
      name: '乳膠漆施工',
      spec: '新作全批土',
      unit: '坪',
      suggestedPrice: 1900,
      price: 1900,
      note: '連工帶料',
      regulation: '批土→打磨→底漆→面漆',
    },
    {
      id: 307,
      name: '乳膠漆施工',
      spec: '舊面修補',
      unit: '坪',
      suggestedPrice: 1450,
      price: 1450,
      note: '連工帶料',
      regulation: '舊面需刮除鬆動漆膜',
    },
    {
      id: 308,
      name: '水泥漆施工',
      spec: '新作全批土',
      unit: '坪',
      suggestedPrice: 1400,
      price: 1400,
      note: '連工帶料',
      regulation: '水泥漆經濟實惠但透氣性差',
    },
    {
      id: 309,
      name: '水泥漆施工',
      spec: '舊面修補',
      unit: '坪',
      suggestedPrice: 1050,
      price: 1050,
      note: '連工帶料',
      regulation: '',
    },
    {
      id: 310,
      name: '天花板粉刷',
      spec: '平頂',
      unit: '坪',
      suggestedPrice: 350,
      price: 350,
      note: '純工資',
      regulation: '天花板施工需注意照明遮蔽',
    },
  ],
  // ===== 室內裝潢 - 木作工程 =====
  木作: [
    {
      id: 321,
      name: '木芯板',
      spec: '4x8呎/18mm',
      unit: '片',
      suggestedPrice: 800,
      price: 800,
      note: '36才/片',
      regulation: 'CNS 1349：木芯板規範',
    },
    {
      id: 322,
      name: '夾板',
      spec: '4x8呎/18mm',
      unit: '片',
      suggestedPrice: 450,
      price: 450,
      note: '36才/片',
      regulation: 'CNS 1349：結構用夾板',
    },
    {
      id: 323,
      name: '角材',
      spec: '1.2x1.2寸/12尺',
      unit: '支',
      suggestedPrice: 35,
      price: 35,
      note: '柳安',
      regulation: '角材間距≤30cm為佳',
    },
    {
      id: 324,
      name: '線板',
      spec: '椴木/塑膠',
      unit: '尺',
      suggestedPrice: 80,
      price: 80,
      note: '收邊用',
      regulation: '線板用於收邊修飾',
    },
    {
      id: 325,
      name: '平釘天花板',
      spec: '矽酸鈣板+角料',
      unit: '坪',
      suggestedPrice: 4500,
      price: 4500,
      note: '連工帶料',
      regulation: '矽酸鈣板需為耐燃一級',
    },
    {
      id: 326,
      name: '造型天花板',
      spec: '含間接照明',
      unit: '坪',
      suggestedPrice: 6500,
      price: 6500,
      note: '連工帶料',
      regulation: '間接照明需預留維修孔',
    },
    {
      id: 327,
      name: '木作門框',
      spec: '實木貼皮',
      unit: '樘',
      suggestedPrice: 8000,
      price: 8000,
      note: '含安裝',
      regulation: '門框需考慮防火等級',
    },
    {
      id: 328,
      name: '木作門片',
      spec: '推門',
      unit: '樘',
      suggestedPrice: 12000,
      price: 12000,
      note: '含五金',
      regulation: '室內門高度建議≥210cm',
    },
    {
      id: 329,
      name: '木作開門',
      spec: '門框+門片',
      unit: '樘',
      suggestedPrice: 18000,
      price: 18000,
      note: '連工帶料',
      regulation: '開門淨寬≥80cm（無障礙）',
    },
    {
      id: 330,
      name: '木作櫃體',
      spec: '衣櫃/書櫃',
      unit: '尺',
      suggestedPrice: 7500,
      price: 7500,
      note: '連工帶料',
      regulation: '固定式櫃體需錨固牆面',
    },
    {
      id: 331,
      name: '木作電視櫃',
      spec: '含背板處理',
      unit: '尺',
      suggestedPrice: 6500,
      price: 6500,
      note: '連工帶料',
      regulation: '電視櫃需預留走線孔',
    },
    {
      id: 332,
      name: '木地板鋪設',
      spec: '純工資',
      unit: '坪',
      suggestedPrice: 1200,
      price: 1200,
      note: '卡扣式',
      regulation: '木地板需預留伸縮縫',
    },
  ],
  // ===== 室內裝潢 - 系統櫃 =====
  系統櫃: [
    {
      id: 341,
      name: '塑合板櫃體',
      spec: 'E1級',
      unit: '尺',
      suggestedPrice: 2800,
      price: 2800,
      note: '基本款',
      regulation: 'E1級甲醛釋出量≤0.1ppm',
    },
    {
      id: 342,
      name: '木心板櫃體',
      spec: '防潮',
      unit: '尺',
      suggestedPrice: 3500,
      price: 3500,
      note: '中階款',
      regulation: '木心板承重較佳',
    },
    {
      id: 343,
      name: '發泡板櫃體',
      spec: '防水',
      unit: '尺',
      suggestedPrice: 4200,
      price: 4200,
      note: '浴室廚房',
      regulation: '發泡板100%防水',
    },
    {
      id: 344,
      name: '平板門片',
      spec: '塑合板',
      unit: '才',
      suggestedPrice: 180,
      price: 180,
      note: '基本款',
      regulation: '',
    },
    {
      id: 345,
      name: '造型門片',
      spec: '吸塑/烤漆',
      unit: '才',
      suggestedPrice: 350,
      price: 350,
      note: '中高階',
      regulation: '烤漆門片較耐刮',
    },
    {
      id: 346,
      name: '玻璃門片',
      spec: '鋁框+玻璃',
      unit: '才',
      suggestedPrice: 280,
      price: 280,
      note: '透視展示',
      regulation: '玻璃需為強化或膠合',
    },
    {
      id: 347,
      name: '緩衝鉸鏈',
      spec: '西德/Blum',
      unit: '組',
      suggestedPrice: 200,
      price: 200,
      note: '進口五金',
      regulation: '緩衝鉸鏈延長櫃體壽命',
    },
    {
      id: 348,
      name: '三節滑軌',
      spec: '緩衝',
      unit: '組',
      suggestedPrice: 350,
      price: 350,
      note: '抽屜用',
      regulation: '滑軌承重需注意',
    },
    {
      id: 349,
      name: '衣櫃拉籃',
      spec: '不鏽鋼',
      unit: '組',
      suggestedPrice: 1200,
      price: 1200,
      note: '含滑軌',
      regulation: '',
    },
    {
      id: 350,
      name: '系統衣櫃',
      spec: '240cm高',
      unit: '尺',
      suggestedPrice: 4500,
      price: 4500,
      note: '連工帶料',
      regulation: '衣櫃需固定於牆面防傾倒',
    },
    {
      id: 351,
      name: '系統書櫃',
      spec: '含門片',
      unit: '尺',
      suggestedPrice: 3800,
      price: 3800,
      note: '連工帶料',
      regulation: '書櫃層板間距考慮書本高度',
    },
    {
      id: 352,
      name: '系統鞋櫃',
      spec: '含通風',
      unit: '尺',
      suggestedPrice: 3200,
      price: 3200,
      note: '連工帶料',
      regulation: '鞋櫃需通風設計',
    },
  ],
  // ===== 室內裝潢 - 水電工程 =====
  水電: [
    {
      id: 361,
      name: '電線 2.0mm',
      spec: '單芯線',
      unit: '尺',
      suggestedPrice: 8,
      price: 8,
      note: '插座/照明',
      regulation: '一般照明迴路用2.0mm',
    },
    {
      id: 362,
      name: '電線 5.5mm',
      spec: '單芯線',
      unit: '尺',
      suggestedPrice: 20,
      price: 20,
      note: '專用迴路',
      regulation: '冷氣/電熱器專用迴路需5.5mm',
    },
    {
      id: 363,
      name: 'PVC管 3/4吋',
      spec: '4米長',
      unit: '支',
      suggestedPrice: 45,
      price: 45,
      note: '電線管',
      regulation: '電線需配管保護',
    },
    {
      id: 364,
      name: '開關',
      spec: '國際牌/含安裝',
      unit: '組',
      suggestedPrice: 180,
      price: 180,
      note: '單切/三路',
      regulation: '開關高度建議離地120cm',
    },
    {
      id: 365,
      name: '插座',
      spec: '國際牌/含安裝',
      unit: '組',
      suggestedPrice: 180,
      price: 180,
      note: '接地型',
      regulation: '浴室/廚房需接地型插座',
    },
    {
      id: 366,
      name: '專用迴路',
      spec: '冷氣/廚房',
      unit: '迴',
      suggestedPrice: 3000,
      price: 3000,
      note: '含無熔絲開關',
      regulation: '大功率電器需專用迴路',
    },
    {
      id: 367,
      name: '配電盤',
      spec: '12迴路',
      unit: '組',
      suggestedPrice: 8000,
      price: 8000,
      note: '含安裝',
      regulation: '配電盤需接地，迴路數足夠',
    },
    {
      id: 368,
      name: '燈具安裝',
      spec: '一般',
      unit: '盞',
      suggestedPrice: 500,
      price: 500,
      note: '純工資',
      regulation: '',
    },
    {
      id: 369,
      name: '燈具安裝',
      spec: '崁燈',
      unit: '盞',
      suggestedPrice: 350,
      price: 350,
      note: '純工資',
      regulation: '崁燈需注意天花板耐燃',
    },
    {
      id: 370,
      name: 'LED燈條',
      spec: '每米',
      unit: 'm',
      suggestedPrice: 250,
      price: 250,
      note: '含變壓器',
      regulation: 'LED變壓器需UL認證',
    },
    {
      id: 371,
      name: '冷水管重拉',
      spec: '不鏽鋼管',
      unit: '處',
      suggestedPrice: 2500,
      price: 2500,
      note: '含打牆/復原',
      regulation: '不鏽鋼管耐久性佳',
    },
    {
      id: 372,
      name: '熱水管重拉',
      spec: '被覆銅管',
      unit: '處',
      suggestedPrice: 5000,
      price: 5000,
      note: '含打牆/復原',
      regulation: '熱水管需保溫處理',
    },
    {
      id: 373,
      name: '排水管',
      spec: '2吋PVC',
      unit: '處',
      suggestedPrice: 1800,
      price: 1800,
      note: '含接頭',
      regulation: '排水管需坡度≥1/50',
    },
    {
      id: 374,
      name: '馬桶',
      spec: '二段式沖水',
      unit: '組',
      suggestedPrice: 8000,
      price: 8000,
      note: '含安裝',
      regulation: '二段式沖水省水標章',
    },
    {
      id: 375,
      name: '臉盆',
      spec: '標準型',
      unit: '組',
      suggestedPrice: 4000,
      price: 4000,
      note: '含龍頭',
      regulation: '龍頭建議省水標章',
    },
    {
      id: 376,
      name: '淋浴設備',
      spec: '花灑組',
      unit: '組',
      suggestedPrice: 6000,
      price: 6000,
      note: '含安裝',
      regulation: '淋浴區需獨立排水',
    },
  ],
  // ===== 室內裝潢 - 地板工程 =====
  地板: [
    {
      id: 381,
      name: 'SPC石塑地板',
      spec: '卡扣式',
      unit: '坪',
      suggestedPrice: 2500,
      price: 2500,
      note: '防水/耐磨',
      regulation: 'SPC地板100%防水，適合浴室',
    },
    {
      id: 382,
      name: '超耐磨地板',
      spec: '卡扣式',
      unit: '坪',
      suggestedPrice: 4500,
      price: 4500,
      note: '木紋/石紋',
      regulation: '超耐磨係數AC4以上',
    },
    {
      id: 383,
      name: '海島型木地板',
      spec: '複合實木',
      unit: '坪',
      suggestedPrice: 8000,
      price: 8000,
      note: '含安裝',
      regulation: '海島型適合台灣氣候',
    },
    {
      id: 384,
      name: '實木地板',
      spec: '柚木/橡木',
      unit: '坪',
      suggestedPrice: 12000,
      price: 12000,
      note: '含安裝',
      regulation: '實木需定期保養上蠟',
    },
    {
      id: 385,
      name: '拋光石英磚',
      spec: '60x60cm',
      unit: '坪',
      suggestedPrice: 5500,
      price: 5500,
      note: '連工帶料',
      regulation: '石英磚吸水率≤0.5%',
    },
    {
      id: 386,
      name: '拋光石英磚',
      spec: '80x80cm',
      unit: '坪',
      suggestedPrice: 7500,
      price: 7500,
      note: '連工帶料',
      regulation: '大尺寸需乾式施工',
    },
    {
      id: 387,
      name: '大理石地板',
      spec: '國產',
      unit: '坪',
      suggestedPrice: 15000,
      price: 15000,
      note: '連工帶料',
      regulation: '大理石需定期拋光保養',
    },
    {
      id: 388,
      name: '大理石地板',
      spec: '進口',
      unit: '坪',
      suggestedPrice: 35000,
      price: 35000,
      note: '連工帶料',
      regulation: '進口石材需確認紋路',
    },
    {
      id: 389,
      name: '地板起翹修復',
      spec: '局部',
      unit: '坪',
      suggestedPrice: 2000,
      price: 2000,
      note: '純工資',
      regulation: '起翹原因需先排除',
    },
    {
      id: 390,
      name: '地板打蠟',
      spec: '保養',
      unit: '坪',
      suggestedPrice: 150,
      price: 150,
      note: '純工資',
      regulation: '實木地板每年打蠟1-2次',
    },
  ],
  // ===== 室內裝潢 - 玻璃工程 =====
  玻璃: [
    {
      id: 401,
      name: '清玻璃 5mm',
      spec: '一般',
      unit: '才',
      suggestedPrice: 35,
      price: 35,
      note: '隔間',
      regulation: 'CNS 679：平板玻璃',
    },
    {
      id: 402,
      name: '強化玻璃 8mm',
      spec: '淋浴',
      unit: '才',
      suggestedPrice: 70,
      price: 70,
      note: '安全',
      regulation: 'CNS 2213：強化玻璃規範',
    },
    {
      id: 403,
      name: '強化玻璃 10mm',
      spec: '淋浴門',
      unit: '才',
      suggestedPrice: 90,
      price: 90,
      note: '厚實',
      regulation: '淋浴門建議10mm以上',
    },
    {
      id: 404,
      name: '膠合玻璃 5+5mm',
      spec: '安全',
      unit: '才',
      suggestedPrice: 120,
      price: 120,
      note: '防盜',
      regulation: 'CNS 14815：膠合安全玻璃',
    },
    {
      id: 405,
      name: '烤漆玻璃 5mm',
      spec: '廚房背牆',
      unit: '才',
      suggestedPrice: 150,
      price: 150,
      note: '易清潔',
      regulation: '烤漆玻璃耐熱易清潔',
    },
    {
      id: 406,
      name: '茶玻/灰玻 5mm',
      spec: '隔間',
      unit: '才',
      suggestedPrice: 55,
      price: 55,
      note: '半透明',
      regulation: '有色玻璃透光率依顏色',
    },
    {
      id: 407,
      name: '鏡子 5mm',
      spec: '銀鏡',
      unit: '才',
      suggestedPrice: 80,
      price: 80,
      note: '浴室/穿衣',
      regulation: '浴室鏡需防潮處理',
    },
    {
      id: 408,
      name: '玻璃隔間',
      spec: '含鋁框',
      unit: '才',
      suggestedPrice: 250,
      price: 250,
      note: '連工帶料',
      regulation: '玻璃隔間需考慮隔音',
    },
    {
      id: 409,
      name: '玻璃拉門',
      spec: '軌道式',
      unit: '才',
      suggestedPrice: 320,
      price: 320,
      note: '含五金',
      regulation: '拉門軌道需承重足夠',
    },
    {
      id: 410,
      name: '淋浴拉門',
      spec: '含五金',
      unit: '組',
      suggestedPrice: 18000,
      price: 18000,
      note: '90cm寬',
      regulation: '淋浴門需強化/膠合玻璃',
    },
  ],
  // ===== 室內裝潢 - 輕鋼架隔間 =====
  輕鋼架: [
    // --- 骨架材料 ---
    {
      id: 501,
      name: 'C型立柱 C65',
      spec: '65mm寬 × 0.8mm厚 × 3M',
      unit: '支',
      suggestedPrice: 85,
      price: 85,
      note: '熱浸鍍鋅/一般隔間',
      regulation: 'CNS 1244 G3027：熱浸鍍鋅鋼板，立柱間距≤610mm',
    },
    {
      id: 502,
      name: 'C型立柱 C75',
      spec: '75mm寬 × 0.8mm厚 × 3M',
      unit: '支',
      suggestedPrice: 95,
      price: 95,
      note: '熱浸鍍鋅/標準隔間',
      regulation: 'CNS 11984：W-75型輕鋼架組合規範',
    },
    {
      id: 503,
      name: 'C型立柱 C92',
      spec: '92mm寬 × 1.0mm厚 × 3M',
      unit: '支',
      suggestedPrice: 130,
      price: 130,
      note: '熱浸鍍鋅/高隔音隔間',
      regulation: 'CNS 11984：較厚立柱適用隔音需求，STC≥45',
    },
    {
      id: 504,
      name: 'C型立柱 C100',
      spec: '100mm寬 × 1.0mm厚 × 3M',
      unit: '支',
      suggestedPrice: 150,
      price: 150,
      note: '熱浸鍍鋅/高度>4M用',
      regulation: 'CNS 11984 W-100型：間柱>4M需採用此規格',
    },
    {
      id: 505,
      name: 'U型上槽',
      spec: '配合C柱寬度 × 3M',
      unit: '支',
      suggestedPrice: 75,
      price: 75,
      note: '固定於天花板',
      regulation: '上下槽以火藥擊釘固定，間距≤60cm',
    },
    {
      id: 506,
      name: 'U型下槽',
      spec: '配合C柱寬度 × 3M',
      unit: '支',
      suggestedPrice: 75,
      price: 75,
      note: '固定於地板',
      regulation: '下槽需確保水平，偏差≤3mm/M',
    },
    {
      id: 507,
      name: '橫撐鐵件',
      spec: '80cm/120cm高度',
      unit: '支',
      suggestedPrice: 45,
      price: 45,
      note: '水平補強/掛物用',
      regulation: '自地面80cm或120cm處加設，增加結構穩定性',
    },
    {
      id: 508,
      name: '補強角鐵',
      spec: 'L型/門框轉角',
      unit: '支',
      suggestedPrice: 35,
      price: 35,
      note: '門框/轉角補強',
      regulation: '門窗開口、轉角處需加設立柱補強',
    },
    {
      id: 509,
      name: '火藥擊釘',
      spec: '27mm (混凝土用)',
      unit: '盒/100支',
      suggestedPrice: 280,
      price: 280,
      note: '固定上下槽用',
      regulation: '擊釘間距≤60cm，需佩戴護目鏡施工',
    },
    {
      id: 510,
      name: '攻牙螺絲',
      spec: '3.5×25mm (自攻)',
      unit: '盒/1000支',
      suggestedPrice: 350,
      price: 350,
      note: '封板用/間距20cm',
      regulation: '螺絲間距≤20cm，距板邊≥10mm，頭略凹入板面',
    },
    // --- 板材 ---
    {
      id: 511,
      name: '石膏板 9mm',
      spec: '4×8尺 (1220×2440mm)',
      unit: '片',
      suggestedPrice: 280,
      price: 280,
      note: '經濟型/天花板',
      regulation: 'CNS 4458：石膏板規範，9mm為耐燃二級',
    },
    {
      id: 512,
      name: '石膏板 12mm',
      spec: '4×8尺 (1220×2440mm)',
      unit: '片',
      suggestedPrice: 380,
      price: 380,
      note: '標準隔間牆',
      regulation: 'CNS 4458：12mm以上為耐燃一級，防火時效1hr',
    },
    {
      id: 513,
      name: '石膏板 15mm',
      spec: '4×8尺 (防火型)',
      unit: '片',
      suggestedPrice: 520,
      price: 520,
      note: '防火隔間牆',
      regulation: '建築技術規則：不具承重防火牆建議15mm以上',
    },
    {
      id: 514,
      name: '矽酸鈣板 6mm',
      spec: '4×8尺 (1220×2440mm)',
      unit: '片',
      suggestedPrice: 420,
      price: 420,
      note: '天花板/輕載牆',
      regulation: 'CNS 13777：矽酸鈣板規範，耐燃一級',
    },
    {
      id: 515,
      name: '矽酸鈣板 9mm',
      spec: '4×8尺 (1220×2440mm)',
      unit: '片',
      suggestedPrice: 580,
      price: 580,
      note: '標準隔間/浴室',
      regulation: 'CNS 13777：9mm防火時效1hr，抗彎≥130kgf/cm²',
    },
    {
      id: 516,
      name: '矽酸鈣板 12mm',
      spec: '4×8尺 (1220×2440mm)',
      unit: '片',
      suggestedPrice: 780,
      price: 780,
      note: '高防火/公共空間',
      regulation: 'CNS 13777：12mm防火時效2hr，建議公共區域使用',
    },
    {
      id: 517,
      name: '纖維水泥板 6mm',
      spec: '4×8尺 (耐燃一級)',
      unit: '片',
      suggestedPrice: 450,
      price: 450,
      note: '外牆/潮濕區',
      regulation: 'CNS 3802：纖維水泥板規範，≥6mm',
    },
    {
      id: 518,
      name: '木絲水泥板 16mm',
      spec: '4×8尺 (吸音型)',
      unit: '片',
      suggestedPrice: 650,
      price: 650,
      note: '吸音天花板/牆面',
      regulation: 'CNS 14705：木絲水泥板≥16mm，NRC吸音係數≥0.65',
    },
    // --- 填充/配件 ---
    {
      id: 521,
      name: '玻璃棉 50mm',
      spec: '24K密度 (1200×600mm)',
      unit: '片',
      suggestedPrice: 85,
      price: 85,
      note: '隔熱吸音填充',
      regulation: 'CNS 9042：礦物棉規範，填充於骨架內提升隔音STC+5~10',
    },
    {
      id: 522,
      name: '岩棉 50mm',
      spec: '40K密度 (1200×600mm)',
      unit: '片',
      suggestedPrice: 120,
      price: 120,
      note: '防火隔音填充',
      regulation: 'CNS 9042：岩棉耐溫>600°C，A1級不燃材料',
    },
    {
      id: 523,
      name: '吸音棉 25K',
      spec: '25mm厚 (經濟型)',
      unit: 'm²',
      suggestedPrice: 45,
      price: 45,
      note: '基本隔音需求',
      regulation: '填滿骨架空隙可提升隔音約3-5dB',
    },
    {
      id: 524,
      name: '批土帶',
      spec: '紙帶 (50mm×90M)',
      unit: '卷',
      suggestedPrice: 65,
      price: 65,
      note: '接縫處理',
      regulation: '板材接縫需貼帶+批土，防止裂縫',
    },
    {
      id: 525,
      name: '批土 (石膏板用)',
      spec: '25kg/包',
      unit: '包',
      suggestedPrice: 320,
      price: 320,
      note: '接縫/螺絲孔填補',
      regulation: '批土需分2-3次薄批，避免一次過厚',
    },
    {
      id: 526,
      name: '矽利康 (接縫用)',
      spec: '中性 300ml',
      unit: '支',
      suggestedPrice: 85,
      price: 85,
      note: '伸縮縫填充',
      regulation: '板材與板材間預留2-3mm伸縮縫',
    },
    // --- 工資 ---
    {
      id: 531,
      name: '輕鋼架骨架施工',
      spec: '純工資 (含上下槽+立柱)',
      unit: 'm²',
      suggestedPrice: 350,
      price: 350,
      note: '不含材料',
      regulation: '放樣→固定上下槽→立柱安裝→橫撐補強',
    },
    // --- 天花板骨架 ---
    {
      id: 601,
      name: '天花板主架',
      spec: 'T-bar 主骨 (3.6M)',
      unit: '支',
      suggestedPrice: 65,
      price: 65,
      note: '鍍鋅烤漆',
      regulation: '主架間距約120cm，吊桿間距≤120cm',
    },
    {
      id: 602,
      name: '天花板副架',
      spec: 'T-bar 副骨 (60cm)',
      unit: '支',
      suggestedPrice: 25,
      price: 25,
      note: '鍍鋅烤漆',
      regulation: '副架橫向連接主架，形成60x60cm格柵',
    },
    {
      id: 603,
      name: '天花板邊條',
      spec: 'L型邊條 (3M)',
      unit: '支',
      suggestedPrice: 45,
      price: 45,
      note: '沿牆固定',
      regulation: '邊條需水平固定於牆面，以火藥擊釘間距≤50cm',
    },
    {
      id: 604,
      name: '吊桿',
      spec: '304不鏽鋼 (1M)',
      unit: '支',
      suggestedPrice: 35,
      price: 35,
      note: '含膨脹螺絲',
      regulation: '吊桿間距≤120cm，載重≥25kg/m²',
    },
    {
      id: 605,
      name: '調整夾',
      spec: '彈簧調整器',
      unit: '個',
      suggestedPrice: 15,
      price: 15,
      note: '水平調整用',
      regulation: '可調整吊桿長度以校正水平',
    },
    // --- 明架天花板板材 ---
    {
      id: 551,
      name: '明架石膏板',
      spec: '60×60cm (9mm厚)',
      unit: '片',
      suggestedPrice: 45,
      price: 45,
      note: '白色平面',
      regulation: 'CNS 4458：乾式施工，可獨立拆卸維修',
    },
    {
      id: 552,
      name: '明架石膏板',
      spec: '60×60cm (沖孔吸音)',
      unit: '片',
      suggestedPrice: 75,
      price: 75,
      note: 'NRC 0.55',
      regulation: 'CNS 4458：沖孔設計提升吸音性能',
    },
    {
      id: 553,
      name: '明架礦纖板',
      spec: '60×60cm (15mm厚)',
      unit: '片',
      suggestedPrice: 85,
      price: 85,
      note: '高吸音/辦公室',
      regulation: 'CNS標準礦纖板，NRC≥0.55，適用辦公空間',
    },
    {
      id: 554,
      name: '明架矽酸鈣板',
      spec: '60×60cm (6mm厚)',
      unit: '片',
      suggestedPrice: 65,
      price: 65,
      note: '防潮/防火',
      regulation: 'CNS 13777：耐燃一級，適用潮濕區域',
    },
    // --- PVC天花板 ---
    {
      id: 571,
      name: 'PVC長條板',
      spec: '20cm寬×3M (8mm厚)',
      unit: '支',
      suggestedPrice: 85,
      price: 85,
      note: '白色素面',
      regulation: '防水不吸水，適用浴室廚房，壽命約3-5年',
    },
    {
      id: 572,
      name: 'PVC長條板',
      spec: '20cm寬×3M (木紋)',
      unit: '支',
      suggestedPrice: 120,
      price: 120,
      note: '仿木紋理',
      regulation: 'PVC仿木紋，免上漆維護方便',
    },
    {
      id: 573,
      name: 'PVC長條板',
      spec: '25cm寬×4M (8mm厚)',
      unit: '支',
      suggestedPrice: 135,
      price: 135,
      note: '加寬版',
      regulation: '較寬板材減少接縫，視覺更整齊',
    },
    {
      id: 574,
      name: 'PVC收邊條',
      spec: 'U型收邊 (3M)',
      unit: '支',
      suggestedPrice: 45,
      price: 45,
      note: '邊緣封邊',
      regulation: '邊緣收邊處理，提升美觀',
    },
    {
      id: 575,
      name: 'PVC角線',
      spec: '陰角/陽角 (3M)',
      unit: '支',
      suggestedPrice: 35,
      price: 35,
      note: '轉角修飾',
      regulation: '轉角處需使用角線收邊',
    },
    // --- 天花板工資 ---
    {
      id: 581,
      name: '明架天花板',
      spec: '連工帶料 (石膏板)',
      unit: '坪',
      suggestedPrice: 1200,
      price: 1200,
      note: '含骨架+板材',
      regulation: '明架施工快速，維修便利，適用辦公商空',
    },
    {
      id: 582,
      name: '明架天花板',
      spec: '連工帶料 (礦纖板)',
      unit: '坪',
      suggestedPrice: 1400,
      price: 1400,
      note: '含骨架+板材',
      regulation: '礦纖板吸音性佳，NRC≥0.55',
    },
    {
      id: 583,
      name: '明架天花板',
      spec: '連工帶料 (矽酸鈣板)',
      unit: '坪',
      suggestedPrice: 1350,
      price: 1350,
      note: '含骨架+板材',
      regulation: '矽酸鈣板防潮，適用潮濕環境',
    },
    {
      id: 584,
      name: '暗架天花板',
      spec: '連工帶料 (石膏板9mm)',
      unit: '坪',
      suggestedPrice: 1600,
      price: 1600,
      note: '含批土油漆',
      regulation: '暗架平整美觀，需批土+油漆',
    },
    {
      id: 585,
      name: '暗架天花板',
      spec: '連工帶料 (矽酸鈣板6mm)',
      unit: '坪',
      suggestedPrice: 1800,
      price: 1800,
      note: '含批土油漆',
      regulation: '矽酸鈣板耐潮，浴室可用',
    },
    {
      id: 586,
      name: '暗架天花板',
      spec: '連工帶料 (矽酸鈣板9mm)',
      unit: '坪',
      suggestedPrice: 2000,
      price: 2000,
      note: '高規格/防火',
      regulation: 'CNS 13777：9mm防火1hr',
    },
    {
      id: 587,
      name: 'PVC天花板',
      spec: '連工帶料 (素色)',
      unit: '坪',
      suggestedPrice: 2100,
      price: 2100,
      note: '含骨架+PVC板',
      regulation: 'PVC防水適用浴室，注意通風散熱',
    },
    {
      id: 588,
      name: 'PVC天花板',
      spec: '連工帶料 (木紋)',
      unit: '坪',
      suggestedPrice: 2400,
      price: 2400,
      note: '含骨架+PVC板',
      regulation: 'PVC木紋仿實木效果',
    },
    {
      id: 589,
      name: '造型天花板',
      spec: '間接照明層板',
      unit: '尺',
      suggestedPrice: 850,
      price: 850,
      note: '含LED燈槽',
      regulation: '間接照明需預留燈槽空間≥15cm',
    },
    {
      id: 590,
      name: '造型天花板',
      spec: '弧形/波浪造型',
      unit: '坪',
      suggestedPrice: 6500,
      price: 6500,
      note: '特殊工法',
      regulation: '造型天花需專業師傅，工期較長',
    },
    {
      id: 591,
      name: '維修孔',
      spec: '60×60cm (含框)',
      unit: '組',
      suggestedPrice: 450,
      price: 450,
      note: '檢修用',
      regulation: '管線集中處需預留維修孔',
    },
  ],
  // ===== 室內裝潢 - 輕隔間牆 =====
  輕隔間: [
    // --- 單面封板 ---
    {
      id: 701,
      name: '單面封板',
      spec: '純工資 (含批土)',
      unit: 'm²',
      suggestedPrice: 280,
      price: 280,
      note: '不含材料',
      regulation: '螺絲間距≤20cm，兩側接縫位置需錯開',
    },
    {
      id: 702,
      name: '單面封板 (石膏板)',
      spec: '連工帶料 12mm石膏板',
      unit: 'm²',
      suggestedPrice: 600,
      price: 600,
      note: '經濟型',
      regulation: 'CNS 4458：耐燃一級石膏板，適用乾燥環境',
    },
    {
      id: 703,
      name: '單面封板 (矽酸鈣板)',
      spec: '連工帶料 9mm矽酸鈣板',
      unit: 'm²',
      suggestedPrice: 750,
      price: 750,
      note: '耐潮型',
      regulation: 'CNS 13777：矽酸鈣板耐潮性佳，適用浴廚',
    },
    // --- 雙面封板 ---
    {
      id: 700,
      name: '雙面封板',
      spec: '純工資 (含批土+填棉)',
      unit: 'm²',
      suggestedPrice: 520,
      price: 520,
      note: '不含材料',
      regulation: '單側封板→填隔音棉→雙側封板→批土處理',
    },
    {
      id: 704,
      name: '雙面封板 (石膏板)',
      spec: '連工帶料 雙面12mm石膏板',
      unit: 'm²',
      suggestedPrice: 1100,
      price: 1100,
      note: '無骨架/純封板',
      regulation: '適用骨架已存在，雙面封板+批土處理',
    },
    {
      id: 705,
      name: '雙面封板 (矽酸鈣板)',
      spec: '連工帶料 雙面9mm矽酸鈣板',
      unit: 'm²',
      suggestedPrice: 1400,
      price: 1400,
      note: '無骨架/純封板',
      regulation: '矽酸鈣板雙面封，耐潮防火',
    },
    // --- C65輕隔間 (經濟型 完成厚8.5cm) ---
    {
      id: 710,
      name: '輕隔間 (經濟型)',
      spec: '65骨架/雙面9mm石膏板',
      unit: 'm²',
      suggestedPrice: 1400,
      price: 1400,
      note: '完成厚8.7cm/STC~38',
      regulation: '經濟型隔間，適用儲藏室、非隔音需求',
    },
    {
      id: 711,
      name: '輕隔間 (石膏板)',
      spec: '65骨架/雙面12mm石膏板',
      unit: 'm²',
      suggestedPrice: 1600,
      price: 1600,
      note: '完成厚9.1cm/STC~40',
      regulation: 'CNS 4458：12mm石膏板防火1hr',
    },
    {
      id: 712,
      name: '輕隔間 (石膏板+隔音棉)',
      spec: '65骨架/雙面12mm石膏板/24K棉',
      unit: 'm²',
      suggestedPrice: 1800,
      price: 1800,
      note: '完成厚9.1cm/STC~45',
      regulation: '填充24K玻璃棉提升隔音5-8dB',
    },
    {
      id: 713,
      name: '輕隔間 (矽酸鈣板)',
      spec: '65骨架/雙面6mm矽酸鈣板',
      unit: 'm²',
      suggestedPrice: 1600,
      price: 1600,
      note: '完成厚7.7cm/耐潮',
      regulation: 'CNS 13777：6mm矽酸鈣板耐燃一級，適輕載牆',
    },
    {
      id: 714,
      name: '輕隔間 (矽酸鈣板)',
      spec: '65骨架/雙面9mm矽酸鈣板',
      unit: 'm²',
      suggestedPrice: 1800,
      price: 1800,
      note: '完成厚8.5cm/STC~40',
      regulation: 'CNS 13777：9mm防火時效1hr，抗彎≥130kgf/cm²',
    },
    {
      id: 715,
      name: '輕隔間 (矽酸鈣板+隔音棉)',
      spec: '65骨架/雙面9mm矽酸鈣板/24K棉',
      unit: 'm²',
      suggestedPrice: 2200,
      price: 2200,
      note: '完成厚8.5cm/STC~46',
      regulation: '標準住宅隔間推薦配置',
    },
    // --- C75輕隔間 (標準型 完成厚9.5cm) ---
    {
      id: 720,
      name: '輕隔間 (標準型)',
      spec: '75骨架/雙面9mm矽酸鈣板',
      unit: 'm²',
      suggestedPrice: 2000,
      price: 2000,
      note: '完成厚9.5cm/STC~42',
      regulation: 'CNS 11984 W-75型：標準配管空間',
    },
    {
      id: 721,
      name: '輕隔間 (標準+隔音)',
      spec: '75骨架/雙面9mm矽酸鈣板/24K棉',
      unit: 'm²',
      suggestedPrice: 2400,
      price: 2400,
      note: '完成厚9.5cm/STC~48',
      regulation: '一般住宅臥室隔間推薦',
    },
    {
      id: 722,
      name: '輕隔間 (標準+高隔音)',
      spec: '75骨架/雙面9mm矽酸鈣板/48K棉',
      unit: 'm²',
      suggestedPrice: 2800,
      price: 2800,
      note: '完成厚9.5cm/STC~50',
      regulation: '需較高隔私場所，48K高密度吸音棉',
    },
    // --- C92輕隔間 (高規格 完成厚11cm) ---
    {
      id: 730,
      name: '輕隔間 (高規格)',
      spec: '92骨架/雙面9mm矽酸鈣板',
      unit: 'm²',
      suggestedPrice: 2400,
      price: 2400,
      note: '完成厚11.0cm/管線空間大',
      regulation: 'CNS 11984：92骨架容納較大管線',
    },
    {
      id: 731,
      name: '輕隔間 (高隔音)',
      spec: '92骨架/雙面9mm矽酸鈣板/岩棉50K',
      unit: 'm²',
      suggestedPrice: 3200,
      price: 3200,
      note: '完成厚11.0cm/STC~52',
      regulation: '分戶牆/分間牆隔音STC≥45，岩棉耐溫>600°C',
    },
    {
      id: 732,
      name: '輕隔間 (雙層板高隔音)',
      spec: '92骨架/雙面雙層9mm矽酸鈣板/岩棉',
      unit: 'm²',
      suggestedPrice: 4200,
      price: 4200,
      note: '完成厚12.8cm/STC~56',
      regulation: '錄音室/會議室頂級隔音配置',
    },
    // --- C100輕隔間 (特殊用途 完成厚12cm+) ---
    {
      id: 740,
      name: '輕隔間 (超高型)',
      spec: '100骨架/雙面9mm矽酸鈣板',
      unit: 'm²',
      suggestedPrice: 2800,
      price: 2800,
      note: '完成厚12.0cm/高度>4M用',
      regulation: 'CNS 11984 W-100型：間柱>4M需採用此規格',
    },
    {
      id: 741,
      name: '輕隔間 (超高+隔音)',
      spec: '100骨架/雙面9mm矽酸鈣板/岩棉50K',
      unit: 'm²',
      suggestedPrice: 3600,
      price: 3600,
      note: '完成厚12.0cm/STC~52',
      regulation: '高大空間+隔音需求配置',
    },
    // --- 門框補強與附加項目 ---
    {
      id: 750,
      name: '門框開口補強',
      spec: '含門框立柱+橫樑',
      unit: '組',
      suggestedPrice: 800,
      price: 800,
      note: '標準門寬90cm',
      regulation: '門窗開口需雙立柱+橫樑補強，承載門重',
    },
    {
      id: 751,
      name: '電箱開口補強',
      spec: '含補強框',
      unit: '組',
      suggestedPrice: 450,
      price: 450,
      note: '配電箱/弱電箱',
      regulation: '開口周邊需補強處理',
    },
    {
      id: 752,
      name: '隔音毯加強',
      spec: '2mm厚 (加掛)',
      unit: 'm²',
      suggestedPrice: 180,
      price: 180,
      note: 'STC+3~5',
      regulation: '隔音毯可額外提升隔音3-5dB',
    },
  ],
};

// 類別圖示映射
const CATEGORY_ICONS = {
  油漆: Paintbrush,
  木作: Hammer,
  泥作: Layers,
  水電: Wrench,
  玻璃: GlassWater,
  地板: Package,
  輕鋼架: Layers,
  輕隔間: Layers,
};

// 格式化金額
const formatCurrency = amount => {
  return new Intl.NumberFormat('zh-TW', {
    style: 'currency',
    currency: 'TWD',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
};

// 類別映射：從 L2 ID 轉換為顯示名稱 (必須與 DEFAULT_MATERIALS 的 key 一致)
const CATEGORY_ID_TO_LABEL = {
  // 營建工程 L2 → 對應 DEFAULT_MATERIALS 的分類
  concrete: '混凝土', // 混凝土
  rebar: '鋼筋', // 鋼筋
  formwork: '模板', // 模板
  masonry: '泥作材料', // 泥作工程 → 泥作材料
  tile: '磁磚材料', // 磁磚工程 → 磁磚材料
  coating: '塗料材料', // 塗料工程 → 塗料材料
  waterproof: '防水材料', // 防水工程 → 防水材料
  window: '門窗材料', // 門窗工程 → 門窗材料
  demolition: '拆除清運', // 拆除清運
  overview: '建築概估', // 建築概估
  // 室內裝潢 L2 → 對應 DEFAULT_MATERIALS 的分類
  paint: '油漆',
  woodwork: '木作',
  cabinet: '系統櫃', // 系統櫃
  electrical: '水電',
  flooring: '地板',
  glass: '玻璃',
  steelframe: '輕鋼架', // 輕鋼架骨架/板材
  partition: '輕隔間', // 輕隔間牆
};

export { DEFAULT_MATERIALS, CATEGORY_ICONS, CATEGORY_ID_TO_LABEL, formatCurrency };
